 Query 1: High-Level Business Summary
SELECT 
    ROUND(SUM(Total), 2) AS Total_Revenue,
    COUNT(InvoiceId) AS Total_Invoices,
    ROUND(AVG(Total), 2) AS Average_Order_Value,
    COUNT(DISTINCT CustomerId) AS Total_Customers
FROM Invoice;

 Query 2: Top 10 Best-Selling Genres
SELECT 
    g.Name AS Genre_Name,
    SUM(il.Quantity) AS Units_Sold,
    ROUND(SUM(il.UnitPrice * il.Quantity), 2) AS Total_Revenue
FROM InvoiceLine il
JOIN Track t ON il.TrackId = t.TrackId
JOIN Genre g ON t.GenreId = g.GenreId
GROUP BY g.GenreId
ORDER BY Total_Revenue DESC
LIMIT 10;

 Query 3: Most Valuable Customers
SELECT 
    c.CustomerId,
    c.FirstName || ' ' || c.LastName AS Customer_Name,
    c.Country,
    ROUND(SUM(i.Total), 2) AS Total_Spent,
    COUNT(i.InvoiceId) AS Total_Orders
FROM Customer c
JOIN Invoice i ON c.CustomerId = i.CustomerId
GROUP BY c.CustomerId
ORDER BY Total_Spent DESC
LIMIT 10;

Query 4: Sales Breakdown by Country
SELECT 
    BillingCountry AS Country,
    COUNT(DISTINCT CustomerId) AS Customer_Count,
    COUNT(InvoiceId) AS Total_Invoices,
    ROUND(SUM(Total), 2) AS Total_Revenue,
    ROUND(AVG(Total), 2) AS Avg_Order_Value
FROM Invoice
GROUP BY BillingCountry
ORDER BY Total_Revenue DESC;

Query 5: Annual Revenue Growth
SELECT 
    strftime('%Y', InvoiceDate) AS Sales_Year,
    COUNT(InvoiceId) AS Total_Orders,
    ROUND(SUM(Total), 2) AS Annual_Revenue
FROM Invoice
GROUP BY Sales_Year
ORDER BY Sales_Year ASC;

Query 6: Revenue Generated by Artists
SELECT 
    ar.Name AS Artist_Name,
    COUNT(DISTINCT il.InvoiceId) AS Orders_Count,
    SUM(il.Quantity) AS Tracks_Sold,
    ROUND(SUM(il.UnitPrice * il.Quantity), 2) AS Total_Revenue
FROM InvoiceLine il
JOIN Track t ON il.TrackId = t.TrackId
JOIN Album al ON t.AlbumId = al.AlbumId
JOIN Artist ar ON al.ArtistId = ar.ArtistId
GROUP BY ar.ArtistId
ORDER BY Total_Revenue DESC
LIMIT 10;

Query 7: Support Agent Sales Performance
SELECT 
    e.EmployeeId,
    e.FirstName || ' ' || e.LastName AS Sales_Rep,
    e.Title,
    COUNT(DISTINCT c.CustomerId) AS Assigned_Customers,
    COUNT(i.InvoiceId) AS Total_Sales_Made,
    ROUND(SUM(i.Total), 2) AS Total_Revenue_Generated
FROM Employee e
JOIN Customer c ON e.EmployeeId = c.SupportRepId
JOIN Invoice i ON c.CustomerId = i.CustomerId
GROUP BY e.EmployeeId
ORDER BY Total_Revenue_Generated DESC;